baseURL: https://cassiotbatista.github.io
languageCode: en-us
title: Cassio T Batista
theme: "PaperMod"

params:
  params:
    author:
      name: "Cassio T Batista"
      email: "Cassio T Batista"
  homeInfoParams:
    Title: Welcome!
    Content: Hi, this is Cassio :) I work on ML applied to speech processing, if you're curious. This blog is a WIP, so check [@cassota](https://cassota.gitlab.io) out to look into my past. Sometimes I push stuff to [@falabrasil](https://github.com/falabrasil).

  socialIcons: # optional
    - name: "graduation-cap"
      url: "https://scholar.google.com.br/citations?user=_04j8QUAAAAJ"
    - name: "linkedin"
      url: "https://linkedin.com/in/cassiotbatista"
    - name: "github"
      url: "https://github.com/cassiotbatista"
    - name: "youtube"
      url: "https://youtube.com/@cassiotbatista"
    - name: "email"
      url: "mailto:cassiotbatista < at > gmail.com"
