baseURL: https://cassiotbatista.github.io
languageCode: en-us
title: Cassio T Batista
theme: "PaperMod"

menu:
  main:
    - name: About
      url: about
      weight: 1

params:
  params:
    author:
      name: "Cassio T Batista"
      email: "Cassio T Batista"
  homeInfoParams:
    Title: Welcome!
    Content: Hi, this is Cassio :) I work on machine learning applied to speech processing, if you're curious. This blog contains technical deep-dives, research notes, and engineering lessons from my experience. Sometimes I also push stuff to [@falabrasil](https://github.com/falabrasil).

  socialIcons: # optional
    - name: "googlescholar"
      url: "https://scholar.google.com.br/citations?user=_04j8QUAAAAJ"
    - name: "linkedin"
      url: "https://linkedin.com/in/cassiotbatista"
    - name: "github"
      url: "https://github.com/cassiotbatista"
    - name: "youtube"
      url: "https://youtube.com/@cassiotbatista"
    - name: "email"
      url: "mailto:cassiotbatista < at > gmail.com"
